NAME = 
FILES = main.c linking.c create_node.c libft.a printing.c extra.c 
OBJECTS = $(FILES:.c=.o)

all:
	gcc -Wall -Werror -Wextra -I. $(FILES)
g:
	gcc -Wall -Werror -Wextra -I. $(FILES) -g
gg:
	gcc -Wall -Werror -Wextra -I. $(FILES) -g -fsanitize=address
